
package cn.itcast;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IweatherService", targetNamespace = "http://itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IweatherService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "info", targetNamespace = "http://itcast.cn/", className = "cn.itcast.Info")
    @ResponseWrapper(localName = "infoResponse", targetNamespace = "http://itcast.cn/", className = "cn.itcast.InfoResponse")
    public String info(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
